### ISSUE TITLE
Disable dragger

### ISSUE THREAD

**Issue by xApep** [Irfanwani/bottomsheet#1]
How do you disable dragger?

As you can see i want to fill whole modal with background color and without dragger.

<img width="460" alt="image" src="https://user-images.githubusercontent.com/1315340/212389547-d5744bf8-3ecc-402e-ad53-224f398f8844.png">

**Comment by Irfanwani** [comment]
@xApep Sorry but there is no option for this for now, I actually created this npm package for learning only, anyway, I will add the two things in the new update, one is disabling dragger, second will be custom styles for the dragger view.

One more thing, If you want to have same styles for the dragger and the modal view, use the style prop, that will apply styles to both the things.
Thanks for asking here.

**Comment by Irfanwani** [comment]
@xApep Please install the latest version, I added the draggable prop which can be used to show/hide the dragger, + added the styles prop (draggerViewStyle and draggerStyle) for custom styles for dragger container view and dragger icon.

**Comment by Irfanwani** [comment]
Added some more changes too in the new update, and there is still a lot to add to this package, So feel free to start a PR, would be really helpful for me.

**Comment by xApep** [comment]
@Irfanwani thanks for update!

The only thing that its a blocker for me us that you can drag-to-close only if you drag the "dragger area", but if we go into native way; when you long press and drag, it should close bottom sheet.

**Comment by Irfanwani** [comment]
@xApep , thank you so much for the suggestions, if i got you, what you are saying is drag should enable after long press.
Though I haven't seen such behaviour so commonly tbh, but I will add this too, but I would like to add a prop instead of setting this behavior as default as I feel the default one is just drag and close. (I do these things mostly on weekends due to my work in other week days, so please bear with me).

Btw, feel free to contribute to the package if you can help with coding. That would be a great help to my package.

**Comment by Irfanwani** [comment]
I think this problem is solved now in the newer versions, closing this issue
